<br><br><center><h1 style="font-size:2em;color:#2467C0">Tagesaufgaben: Numpy</h1></center>
<br>


## Aufgabe 1

In [ ]:
# Deine Imports:


<div  class="alert alert-block alert-info">
1. Erstelle ein eindimensionales Array und wandel es anschließend in ein zweidimensionales Array der folgenden Form um:

    Output:
    [[12 23]
     [31 25]
     [65 98]]
</div>

<div  class="alert alert-block alert-info">
2. Erstelle ein Array mit den Zahlen 1 bis 100 OHNE den Einsatz von list oder range, ausschließlich mit Numpy-Mitteln. Teile dieses Array danach in zwei gleiche Teile und lege diese auf die Variabeln arr1 und arr2. Lass dir arr1 und arr2 anzeigen.
</div>

<div  class="alert alert-block alert-info">
3. Gegeben ist nachfolgendes Array. Sortiere die Zahlen im Array.

    Output:
    [12 20 23 34]
</div>

In [ ]:
array1 = np.array([20, 23, 12, 34])


<div  class="alert alert-block alert-info">
4. Erstelle zwei Arrays. Füge beide Arrays zusammen. Nutze dafür zwei verschiedene Befehle.

    Output:
    [20 23 12 34 23 34 12 45]
    [20 23 12 34 23 34 12 45]
</div>

<div  class="alert alert-block alert-info">
5. Erstelle ein eindimensionales Array und teile es in zwei Arrays auf. Speichere das Ergebnis der Teilung in zwei Variablen. Nutze dafür nur eine Zeile Code.

    Output:
    [array([20, 23]), array([12, 34])]
</div>

In [ ]:
array1 = np.array([20, 23, 12, 34])


<div  class="alert alert-block alert-info">
6. Gegeben ist folgendes Array. Lass dir die Index-Position ausgeben, an der sich der Name Sara befindet.

    Output:
    (array([1], dtype=int64),)
</div>

In [ ]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])



<div  class="alert alert-block alert-info">
7. Gegeben ist folgendes Array. Durchsuche wieder das Array nach dem Namen Sara aber lass dir dieses Mal eine Liste mit Booleschen Werten für jeden Index des Arrays ausgeben.

    Output:
    [False  True False False False]
</div>

In [ ]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])


<div  class="alert alert-block alert-info">
8. Gegeben ist folgendes Array. Überprüfe, ob in dem Array der Name Hans vorkommt.

    Output:
    False
</div>

In [ ]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])


<div  class="alert alert-block alert-info">
9. Erstelle ein eindimensionales Array mit 8 Zahlen. Lass dir den maximalen Wert und die Summe der Zahlen im Array ausgeben.

    Output:
    67
    206
</div>

In [ ]:
array4 = np.array([20, 23, 12, 34, 45, 67, 2, 3])


<div  class="alert alert-block alert-info">
10. Lass dir den Mittelwert des Arrays aus Aufgabe 9 ausgeben.

    Output:
    25.75
</div>

# Optional

Fasse die Lerninhalte von heute nochmal zusammen und notiere dir Fragen, die dir dabei kommen!