<br><br><center><h1 style="font-size:2em;color:#2467C0">Tagesaufgaben: Numpy</h1></center>
<br>


## Aufgabe 1

In [1]:
# Deine Imports:
import numpy as np
from numpy import dtype
from numpy.ma.core import maximum

<div  class="alert alert-block alert-info">
1. Erstelle ein eindimensionales Array und wandel es anschließend in ein zweidimensionales Array der folgenden Form um:

    Output:
    [[12 23]
     [31 25]
     [65 98]]
</div>

In [58]:
arrayX = np.arange(1, 7)
arrayX_2d = arrayX.reshape((3, 2))
print(arrayX_2d)
arrayX_2d

[[1 2]
 [3 4]
 [5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

<div  class="alert alert-block alert-info">
2. Erstelle ein Array mit den Zahlen 1 bis 100 OHNE den Einsatz von list oder range, ausschließlich mit Numpy-Mitteln. Teile dieses Array danach in zwei gleiche Teile und lege diese auf die Variabeln arr1 und arr2. Lass dir arr1 und arr2 anzeigen.
</div>

In [59]:
array1_100 = np.arange(1, 101)
arr1 = array1_100[0: 50]
arr2 = array1_100[50: ]
print(arr1,"\n\n",arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50] 

 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


<div  class="alert alert-block alert-info">
3. Gegeben ist nachfolgendes Array. Sortiere die Zahlen im Array.

    Output:
    [12 20 23 34]
</div>

In [60]:
array1 = np.array([20, 23, 12, 34])
array1.sort()
print(array1)

[12 20 23 34]


<div  class="alert alert-block alert-info">
4. Erstelle zwei Arrays. Füge beide Arrays zusammen. Nutze dafür zwei verschiedene Befehle.

    Output:
    [20 23 12 34 23 34 12 45]
    [20 23 12 34 23 34 12 45]
</div>

In [61]:
arr01 = np.array([20, 23, 12, 34])
arr02 = np.array([23, 34, 12, 45])
arr03 = np.concatenate((arr01, arr02))
arr04 = np.append(arr01, arr02)
print(arr03)
print(arr04)

[20 23 12 34 23 34 12 45]
[20 23 12 34 23 34 12 45]


<div  class="alert alert-block alert-info">
5. Erstelle ein eindimensionales Array und teile es in zwei Arrays auf. Speichere das Ergebnis der Teilung in zwei Variablen. Nutze dafür nur eine Zeile Code.

    Output:
    [array([20, 23]), array([12, 34])]
</div>

In [62]:
array1 = np.array([20, 23, 12, 34])
arr001, arr002 = np.split(array1, 2)
print(arr001)
print(arr002)

[20 23]
[12 34]


<div  class="alert alert-block alert-info">
6. Gegeben ist folgendes Array. Lass dir die Index-Position ausgeben, an der sich der Name Sara befindet.

    Output:
    (array([1], dtype=int64),)
</div>

In [6]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])
saras_index = np.where(array3 == "Sara")
print(saras_index)

(array([1]),)


<div  class="alert alert-block alert-info">
7. Gegeben ist folgendes Array. Durchsuche wieder das Array nach dem Namen Sara aber lass dir dieses Mal eine Liste mit Booleschen Werten für jeden Index des Arrays ausgeben.

    Output:
    [False  True False False False]
</div>

In [3]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])
array3 == "Sara"

array([False,  True, False, False, False])

<div  class="alert alert-block alert-info">
8. Gegeben ist folgendes Array. Überprüfe, ob in dem Array der Name Hans vorkommt.

    Output:
    False
</div>

In [7]:
array3 = np.array(["Alex", "Sara", "Annika", "Max", "Julian"])
hans = "Hans" in array3
hans

False

<div  class="alert alert-block alert-info">
9. Erstelle ein eindimensionales Array mit 8 Zahlen. Lass dir den maximalen Wert und die Summe der Zahlen im Array ausgeben.

    Output:
    67
    206
</div>

In [27]:
array4 = np.array([20, 23, 12, 34, 45, 67, 2, 3])
print(array4.max())
print(array4.sum())

67
206


<div  class="alert alert-block alert-info">
10. Lass dir den Mittelwert des Arrays aus Aufgabe 9 ausgeben.

    Output:
    25.75
</div>

In [28]:
print(array4.mean())

25.75


# Optional

Fasse die Lerninhalte von heute nochmal zusammen und notiere dir Fragen, die dir dabei kommen!